### ISSUE TITLE
Cannot find module 'stylelint'

### ISSUE THREAD

**Issue by aklkv** [mansona/ember-cli-notifications#92]
After upgrade to v4 when on `ember s` I get:

``` bash

Cannot find module 'stylelint'
Error: Cannot find module 'stylelint'
  at Function.Module._resolveFilename (module.js:440:15)
  at Function.Module._load (module.js:388:25)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Object.<anonymous> (/Users/uni_mac/Desktop/Semios/brae-ember/node_modules/ember-cli-notifications/index.js:14:11)
  at Module._compile (module.js:541:32)
  at Object.Module._extensions..js (module.js:550:10)
  at Module.load (module.js:458:32)
  at tryModuleLoad (module.js:417:12)
  at Function.Module._load (module.js:409:3)
  at Module.require (module.js:468:17)
  at require (internal/module.js:20:19)
  at Function.Addon.lookup (/Users/uni_mac/Desktop/Semios/brae-ember/node_modules/ember-cli/lib/models/addon.js:1002:19)

```

I have installed `stylelint` globally but it did fix the problem.

Thank you.

**Comment by vst** [comment]
Confirmed. I did a fresh installation of `ember-cli @2.7.0` and received same error both with and without `ember-cli-stylelint` installed.

**Comment by ynnoj** [comment]
Fixed in `4.0.1`.
